### ISSUE TITLE
Formatting in annotation formats is not preserved

### ISSUE THREAD

**Issue by Bidski** [bit-bots/imagetagger#46]
When exporting annotations the indentation of each line is not preserved. This breaks formats that rely on indentation to work (like YAML).

For example, a format like this:
```
# Base format
imageset_%%imageset:
    description: %%setdecsription
    team: %%team
    location: %%setlocation
    %%content

# Image format
    %%imagename:
        dimensions: [%%imagewidth, %%imageheight]
        num_annotations: %%annoamount
        %%annotations
```

Produces an output like this:
```
imageset_bitbots-nagoya-01:
    description: %%setdecsription
    team: Bit-Bots
    location: nagoya
    
ball_move_1_00001.png:
        dimensions: [800, 600]
        num_annotations: 5
```

Here, the issue is that `ball_move_1_00001.png:` should be indented to line up with `location`. The same issue occurs with the annotation formats too.

It also appears as though an extra newline is appended to the base format. While this shouldn't break  YAML syntax, it is an unexpected occurrence.
